name: lando-apache-defaults
proxy:
  defaults:
    - landoapache.lndo.site
services:
  defaults:
    type: apache:2.4
  patch:
    type: apache:2.4.64

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/apache": ../..
